
package com.topaiebiz.member.point.crm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactUpsert", targetNamespace = "http://siebel.com/asi/BYM")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ContactUpsert {


    /**
     * 
     * @param babyId
     * @param errDesc
     * @param houseId
     * @param contactId
     * @param errCode
     * @param inXml
     * @param source
     */
    @WebMethod(operationName = "ContactUpsert", action = "rpc/http://siebel.com/asi/BYM:ContactUpsert")
    public void contactUpsert(
            @WebParam(name = "InXml", partName = "InXml")
                    String inXml,
            @WebParam(name = "Source", partName = "Source")
                    String source,
            @WebParam(name = "BabyId", mode = WebParam.Mode.OUT, partName = "BabyId")
                    Holder<String> babyId,
            @WebParam(name = "ContactId", mode = WebParam.Mode.OUT, partName = "ContactId")
                    Holder<String> contactId,
            @WebParam(name = "ErrCode", mode = WebParam.Mode.OUT, partName = "ErrCode")
                    Holder<String> errCode,
            @WebParam(name = "ErrDesc", mode = WebParam.Mode.OUT, partName = "ErrDesc")
                    Holder<String> errDesc,
            @WebParam(name = "HouseId", mode = WebParam.Mode.OUT, partName = "HouseId")
                    Holder<String> houseId);

}
