
package com.topaiebiz.member.point.crm.ws;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRMRedemptionWS", targetNamespace = "http://siebel.com/asi/BYM", wsdlLocation = "http://cardc.motherbuy.com/CRMRedemptionWS.WSDL")
public class CRMRedemptionWS extends Service {

	private static Logger log = LoggerFactory.getLogger(CRMRedemptionWS.class);
	private final static URL CRMREDEMPTIONWS_WSDL_LOCATION;
	private final static WebServiceException CRMREDEMPTIONWS_EXCEPTION;
	private final static QName CRMREDEMPTIONWS_QNAME = new QName("http://siebel.com/asi/BYM", "CRMRedemptionWS");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			// File file=new
			// File("/usr/works/apache-tomcat-7.0.70-cardcore/webapps/CRMRedemptionWS.WSDL");
			url = new URL("http://cardc.motherbuy.com/CRMRedemptionWS.WSDL");
			// url = file.toURL();
		} catch (Exception ex) {
			log.error(ex.getMessage(), ex);
			e = new WebServiceException(ex);
		}
		CRMREDEMPTIONWS_WSDL_LOCATION = url;
		CRMREDEMPTIONWS_EXCEPTION = e;
	}

	public CRMRedemptionWS() {
		super(__getWsdlLocation(), CRMREDEMPTIONWS_QNAME);
	}

	public CRMRedemptionWS(WebServiceFeature... features) {
		super(__getWsdlLocation(), CRMREDEMPTIONWS_QNAME, features);
	}

	public CRMRedemptionWS(URL wsdlLocation) {
		super(wsdlLocation, CRMREDEMPTIONWS_QNAME);
	}

	public CRMRedemptionWS(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, CRMREDEMPTIONWS_QNAME, features);
	}

	public CRMRedemptionWS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CRMRedemptionWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns NewRedemptionOrder
	 */
	@WebEndpoint(name = "NewRedemptionOrder")
	public NewRedemptionOrder getNewRedemptionOrder() {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "NewRedemptionOrder"), NewRedemptionOrder.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns NewRedemptionOrder
	 */
	@WebEndpoint(name = "NewRedemptionOrder")
	public NewRedemptionOrder getNewRedemptionOrder(WebServiceFeature... features) {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "NewRedemptionOrder"), NewRedemptionOrder.class,
				features);
	}

	/**
	 *
	 * @return returns UpdateRedemptionOrder
	 */
	@WebEndpoint(name = "UpdateRedemptionOrder")
	public UpdateRedemptionOrder getUpdateRedemptionOrder() {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "UpdateRedemptionOrder"),
				UpdateRedemptionOrder.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns UpdateRedemptionOrder
	 */
	@WebEndpoint(name = "UpdateRedemptionOrder")
	public UpdateRedemptionOrder getUpdateRedemptionOrder(WebServiceFeature... features) {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "UpdateRedemptionOrder"),
				UpdateRedemptionOrder.class, features);
	}

	/**
	 *
	 * @return returns RedemptionOrderCancel
	 */
	@WebEndpoint(name = "RedemptionOrderCancel")
	public RedemptionOrderCancel getRedemptionOrderCancel() {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "RedemptionOrderCancel"),
				RedemptionOrderCancel.class);
	}

	/**
	 *
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns RedemptionOrderCancel
	 */
	@WebEndpoint(name = "RedemptionOrderCancel")
	public RedemptionOrderCancel getRedemptionOrderCancel(WebServiceFeature... features) {
		return super.getPort(new QName("http://siebel.com/asi/BYM", "RedemptionOrderCancel"),
				RedemptionOrderCancel.class, features);
	}

	private static URL __getWsdlLocation() {
		if (CRMREDEMPTIONWS_EXCEPTION != null) {
			throw CRMREDEMPTIONWS_EXCEPTION;
		}
		return CRMREDEMPTIONWS_WSDL_LOCATION;
	}

}
